### ISSUE TITLE
cannot split in depth more than 8

### ISSUE THREAD

**Issue by YvShu** [WeiJiuQi/DET-LSH#1]
你好作者，我在运行代码时出现了“cannot split in depth more than 8”的错误，请问产生这个问题可能的原因是什么？
目前尝试了deep1M、msong、sift10M数据集，数据格式都是按要求构造的，其中deep1M可以运行：
![image](https://github.com/user-attachments/assets/11364937-0419-4db9-8dda-22fc9c1282a0)
而msong和sift10M数据集都产生了如下问题，参数设置是按要求设置的
![屏幕截图 2024-09-23 162302](https://github.com/user-attachments/assets/47fd996b-736a-4841-9eed-4adcb2518e3d)

**Comment by WeiJiuQi** [comment]
@YvShu 出现此问题的原因可能是树的叶子结点大小参数--leaf-size设置的太小，导致8位的编码空间被快速耗尽，建议可以把--leaf-size调大看是否能解决问题。readme中的--leaf-size设置是接近下界的，如果数据集分布有有波动可能会导致树构建失败，所以实际使用时可以适当增大--leaf-size参数。

**Comment by YvShu** [comment]
@WeiJiuQi 作者你好，经过DEBUG之后我发现了问题所在，无论我设置leaf-size为多少，问题都没有解决，max_leaf_size始终为16
![4930afab-671e-4086-abf9-da382f3d0147](https://github.com/user-attachments/assets/fd73bb6a-8b99-4854-a627-5db8a1538824)
![749133e4-9198-4be2-9417-4711e77aeea7](https://github.com/user-attachments/assets/b34659f5-1c79-43cc-8285-4680faa8ea47)

导致这一问题的原因是DETLSH.cpp代码中少了一个break，leaf_size一直是LSH_dimensionality的值：
![屏幕截图 2024-09-24 185937](https://github.com/user-attachments/assets/98ff41bd-c1cd-4474-a260-3e2cf29dd744)

**Comment by WeiJiuQi** [comment]
@YvShu 感谢你指出我在整理代码时出现的这个错误，目前该bug已修复。
